fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    routing_loader: false
    body_listener: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }