framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    validation:
        email_validation_mode: html5
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        validation:
            not_compromised_password: false
