version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    ports:
      - "8888:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/app
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - .:/app
      - composer:/home/app/cache/composer

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: testapp
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33066:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  composer:
    restart: 'no'
    image: composer/composer
    volumes:
      - .:/app
volumes:
  composer:
  mysql-data:

