Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination:
    exclusion_policy: ALL
    virtual_properties:
        getItems:
            expose: true
            serialized_name: items
            type: array
            groups:
                - paginate
        getPageCount:
            expose: true
            serialized_name: pageCount
            type: integer
            groups:
                - paginate
        getItemNumberPerPage:
            expose: true
            serialized_name: itemsPerPage
            groups:
                - paginate
        getTotalItemCount:
            expose: true
            serialized_name: totalItemCount
            groups:
                - paginate
        getCurrentPageNumber:
            expose: true
            serialized_name: currentPage
            groups:
                - paginate
